// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about: dynamic(() => import("./About")),
  contact: dynamic(() => import("./Contact")),
  hero: dynamic(() => import("./Hero")),
  overview: dynamic(() => import("./Overview")),
  products: dynamic(() => import("./Products")),
  services: dynamic(() => import("./Services")),
  vision_mission: dynamic(() => import("./VisionMission")),
  why_choose_us: dynamic(() => import("./WhyChooseUs")),
};
